// CSM Email Map from Disposition list - LinkedIn.xlsx (SharePoint CSM sheet)
// Maps CSM name (lowercase) to their koenig-solutions.com email
const CSM_EMAIL_MAP = {
  "dheeraj kumar raosaheb patil": "Dheeraj.Patil@koenig-solutions.com",
  "kelly": "kelly@koenig-solutions.com",
  "rimpy srivastava": "rimpy.srivastava@koenig-solutions.com",
  "manish bansal": "manish.bansal@koenig-solutions.com",
  "nikita das": "Nikita.Das@koenig-solutions.com",
  "abhilakh borgohain": "Abhilakh.Borgohain@koenig-solutions.com",
  "divya r": "Divya.R@koenig-solutions.com",
  "rakesh kota amarnath": "Rakesh.K@koenig-solutions.com",
  "nirmala gowda c": "Nirmala.C@koenig-solutions.com",
  "khushi dhingra": "Khushi.Dhingra@koenig-solutions.com",
  "divyesh tiwari": "Divyesh.Tiwari@koenig-solutions.com",
  "akum jung la": "Akum.LA@koenig-solutions.com",
  "sana sadiq pathan": "Sana.Williams@koenig-solutions.com",
  "swati rai": "Swati.Rai@koenig-solutions.com",
  "saif hiyatullaha munshi": "Saif.Munshi@koenig-solutions.com",
  "aditya kumar tiwari": "Aditya.Tiwari@koenig-solutions.com",
  "kevin l": "Kevin.L@koenig-solutions.com",
  "parisha gupta": "Parisha.Gupta@koenig-solutions.com",
  "maitri dipak bhansali": "Maitri.Bhansali@koenig-solutions.com",
  "avni singh": "Avni.Singh@koenig-solutions.com",
  "zaid yousuf wani": "Zaid.Wani@koenig-solutions.com",
  "anchal bhatia": "Anchal.Bhatia@koenig-solutions.com",
  "saurabh banerjee": "saurabh.banerjee@koenig-solutions.com",
  "umar farooq": "Umar.Farooq@koenig-solutions.com",
  "tarun monga": "tarun.monga@koenig-solutions.com",
  "deeksha chaitanya": "Deeksha.Chaitanya@koenig-solutions.com",
  "prity bharti": "Prity.Bharti@koenig-solutions.com",
  "kuldip singh parmar": "Keith.Morris@koenig-solutions.com",
  "pooja chauhan": "pooja.chauhan@koenig-solutions.com",
  "jkd avinakshi": "JKD.Avinakshi@koenig-solutions.com",
  "abhishek r": "Abhishek.R@koenig-solutions.com",
  "tarun dwivedi": "Tarun.Dwivedi@koenig-solutions.com",
  "anika singh rana": "Anika.Rana@koenig-solutions.com",
  "aman sinha": "Aman.Sinha@koenig-solutions.com",
  "gurpreet singh": "Gurpreet.Singh@koenig-solutions.com",
  "rahul singh": "Rahul.Singh@koenig-solutions.com",
  "gurpreet kaur": "Gurpreet.Kaur1@koenig-solutions.com",
  "tamanna alisha": "Tamanna.Alisha@koenig-solutions.com",
  "shalini sharma": "Sandra@koenig-solutions.com",
  "gourav garg": "Gabe.Truner@koenig-solutions.com",
  "prashant verma": "Andy.Sam@koenig-solutions.com",
  "simran dewan": "Simran.Deewan@koenig-solutions.com",
  "ali abdou mohamed mohamed": "Ali.Abdou@koenig-solutions.com",
  // CSMs referenced in lead allocations but not in the CSM Excel tab
  "abhishek g b": "Abhishek.GB@koenig-solutions.com",
  "abir lal mondal": "Abir.Mondal@koenig-solutions.com",
  "alwin pb": "Alwin.PB@koenig-solutions.com",
  "daniel owen nimmo": "Daniel.Nimmo@koenig-solutions.com",
  "dinesh kumar jha": "Dinesh.Jha@koenig-solutions.com",
  "himanshu bhalla": "Himanshu.Bhalla@koenig-solutions.com",
  "jasmeet kaur": "Jasmeet.Kaur@koenig-solutions.com",
  "kunal singh": "Kunal.Singh@koenig-solutions.com",
  "manish chaturvedi": "Manish.Chaturvedi@koenig-solutions.com",
  "mohsin afzal bhat": "Mohsin.Bhat@koenig-solutions.com",
  "neha tripathi": "Neha.Tripathi@koenig-solutions.com",
  "pritesh dadarao burange": "Pritesh.Burange@koenig-solutions.com",
  "ratan priya": "Ratan.Priya@koenig-solutions.com",
  "shaik sumaya parvin": "Shaik.Parvin@koenig-solutions.com",
  "shikha mishra": "Shikha.Mishra@koenig-solutions.com",
  "shiv sompati": "Shiv.Sompati@koenig-solutions.com",
};

// CSM (Customer Success Manager) assignments from leadallocation@koenig-solutions.com emails
// Maps lead email (lowercase) to assigned CSM name
const CSM_MAP = {
  // --- Genuine CSM allocations (52 entries) ---
  "2829016s@student.gla.ac.uk": "Manish Chaturvedi",
  "k.prahlad@nkindia.in": "Shikha Mishra",
  "suraj.k@zerodha.com": "Manish Chaturvedi",
  "siddhesh-sanjay.ghag@capgemini.com": "Gurpreet Kaur",
  "varalakshmi.donaparthi@skillquotientgroup.com": "Shikha Mishra",
  "dhairyavyas@live.com": "Manish Chaturvedi",
  "dashnamurthy@grundfos.com": "Shikha Mishra",
  "mahek.mehta@madhda.com": "Gurpreet Singh",
  "titiksha.kulshrestha@hsbc.co.in": "Alwin Pb",
  "kumari.singh2@bankofbaroda.com": "Kuldip Singh Parmar",
  "kushal.kumarsingh@jll.com": "Mohsin Afzal Bhat",
  "saravanan.gunasekaran@v11tech.com": "Shikha Mishra",
  "prem.chand@torquepharma.com": "Shikha Mishra",
  "rishi.raj@vertiv.com": "Shikha Mishra",
  "vipin.verma@nuvoco.com": "Shaik Sumaya Parvin",
  "sweta.p1811@connect.com": "Umar Farooq",
  "bipindaftardarvf@mitwpu.edu.in": "Rakesh Kota Amarnath",
  "dharmendra@gtrtek.com": "Neha Tripathi",
  "avinash.prasad@pwc.com": "Shiv Sompati",
  "nb2400@iiqf.com": "Gurpreet Singh",
  "ankita.sharma829@fnz.com": "Rimpy Srivastava",
  "katariarajnish0@haier.com": "Manish Bansal",
  "nagesh.ovhal@wuerth.com": "Manish Chaturvedi",
  "praveen.k.tiwari@adityabirla.com": "Abhishek G B",
  "rajdeep.gon@tcs.com": "Kevin L",
  "yash.dange1@1point1.com": "Akum Jung La",
  "mukesh.gupta5@pnb.bank.in": "Divyesh Tiwari",
  "anilkumar.b@waycoolfoods.com": "Kelly",
  "arpana.pandey@cushwake.com": "Saif Hiyatullaha Munshi",
  "suhailahmad.haji@medhajhrms.in": "Ratan Priya",
  "periyasamy@sju.edu.in": "Daniel Owen Nimmo",
  "abhishek.nemiyar@bankofamica.com": "Khushi Dhingra",
  "pparnami@wm.com": "Shikha Mishra",
  "loganathan@synthite.com": "Shikha Mishra",
  "arjun.m@cdac.in": "Shaik Sumaya Parvin",
  "amey.gaurvadkar@ritindia.edu": "Umar Farooq",
  "priyanka.rai@atqor.com": "Rakesh Kota Amarnath",
  "krishna.m@solex.in": "Neha Tripathi",
  "hellotestnw@cognizant.com": "Gurpreet Singh",
  "rtarapatla@deloitte.com": "Prity Bharti",
  "ezekielkoroma@sierra-rutile.com": "Nikita Das",
  "rahultulshidas.dhere@kpmg.co.uk": "Jkd Avinakshi",
  "sarbajit.chakraborty@vedangcellular.in": "Divya R",
  "neelesh.pandey@kyndryl.com": "Abhilakh Borgohain",
  "asvathi.aids@mamcet.com": "Akum Jung La",
  "saranya.lakshman@microland.com": "Divyesh Tiwari",
  "sanjeev_n@msn.com": "Abhishek G B",
  "clinton.sam.rhodus@mahle.com": "Aditya Kumar Tiwari",
  "ntiwari@ismg.io": "Jkd Avinakshi",
  "sagar.pastariya@bajajfinserv.in": "Jkd Avinakshi",
  "padmaja.mudavath@hcltech.con": "Jkd Avinakshi",
  "mathews.nyirenda2@fqml.com": "Swati Rai",
  // --- Round-robin allocated entries (163 entries) ---
  "sudhansu.nanda@morningstar.com": "Dheeraj Kumar Raosaheb Patil",
  "raghupathi.vengala@tcs.com": "Nirmala Gowda C",
  "surjeet.kaur@idp.com": "Sana Sadiq Pathan",
  "vishal.bhattacharjee@nielseniq.com": "Parisha Gupta",
  "asifabbas335@work.com": "Maitri Dipak Bhansali",
  "srinivas.a@gaiansolutions.com": "Avni Singh",
  "sankaranpks@crewhoop.in": "Zaid Yousuf Wani",
  "harish.tamboli@solutechus.com": "Anchal Bhatia",
  "sabuthahir@ccc.net": "Saurabh Banerjee",
  "gautamjyotichutia@email.com": "Tarun Monga",
  "kesavan.n@.co.in": "Deeksha Chaitanya",
  "umesha@saglobal.com": "Pooja Chauhan",
  "rajeesh.v.r@panapps.co": "Abhishek R",
  "skaushik@tenneco.com": "Tarun Dwivedi",
  "skamani@ccillp.in": "Anika Singh Rana",
  "rohit.tiwary@telusdigital.com": "Aman Sinha",
  "vijay.patidar@barodabnpparibas.in": "Rahul Singh",
  "shivappa.kudari@commscope.com": "Tamanna Alisha",
  "mohamediliyas.yasin@trafalgarluxurygroup.com": "Shalini Sharma",
  "dhaarmi@fidesregulatory.com": "Gourav Garg",
  "prashant.kumar3@cyient.com": "Prashant Verma",
  "varun.aggarwal@jindalmumbai.com": "Simran Dewan",
  "hemant.verma@ambit.co": "Ali Abdou Mohamed Mohamed",
  "i.hawaldar@ku.edu.bh": "Abir Lal Mondal",
  "rashmi.gupta@idp.com": "Dinesh Kumar Jha",
  "dileepk@vikrantuniversity.ac.in": "Himanshu Bhalla",
  "surveyorshetty@g.com": "Jasmeet Kaur",
  "navision@simar.co.in": "Kunal Singh",
  "shahbaz@kazirangauniversity.in": "Pritesh Dadarao Burange",
  "anjali.sahu@hcl.com": "Dheeraj Kumar Raosaheb Patil",
  "vijaykanthkn@sagarhospitals.in": "Kelly",
  "shubham.kapoor2@axismaxlife.com": "Rimpy Srivastava",
  "saikrishna.mulupuri@digital-nook.net": "Manish Bansal",
  "mahesh@etcodigital.com": "Nikita Das",
  "asra.fatima@hsbc.com": "Abhilakh Borgohain",
  "hemantyadav.it@charusat.ac.in": "Divya R",
  "pawan.singh3@tcs.com": "Nirmala Gowda C",
  "akshay.pujari@iqvia.com": "Khushi Dhingra",
  "p-seetharamaiah@eisai.ci.n": "Sana Sadiq Pathan",
  "anthony@weg.net": "Swati Rai",
  "gc4@systra.com": "Saif Hiyatullaha Munshi",
  "nikhil.annagandulla@mt.com": "Aditya Kumar Tiwari",
  "monika.behl@vidya-india.org": "Kevin L",
  "amitsambyal@lichenstechnologies.com": "Parisha Gupta",
  "meghna.tiwari-ext@syensqo.com": "Maitri Dipak Bhansali",
  "kitesa.merga@du.edu.et": "Avni Singh",
  "nali@commvault.com": "Zaid Yousuf Wani",
  "vidyanshu.sharma@veripark.com": "Anchal Bhatia",
  "karthick.r@sgsco.com": "Saurabh Banerjee",
  "saloni.goenka@pepsico.com": "Tarun Monga",
  "sundaresan.sankaran@charter.com": "Deeksha Chaitanya",
  "vishal.raj@tagworldwide.com": "Prity Bharti",
  "maara@kkwindsolutions.com": "Kuldip Singh Parmar",
  "archanash@allinonesolution.com": "Pooja Chauhan",
  "devendra.jaiswar@3i-infotech.com": "Abhishek R",
  "anant.kumar@sonnysdirect.com": "Tarun Dwivedi",
  "sandeep2@interfaceauto.com": "Anika Singh Rana",
  "waris.mustafa@columbia.com": "Aman Sinha",
  "parvez.khan@munichmotors.com": "Rahul Singh",
  "amarendra.b.kumar@accenture.com": "Gurpreet Kaur",
  "bhargav.harmani@in4velocity.com": "Tamanna Alisha",
  "dgowda@lenovo.com": "Shalini Sharma",
  "tanuku.sreedivya@hcltech.com": "Gourav Garg",
  "info@relonissolutions.com": "Prashant Verma",
  "anuradha.gampa1@tcs.com": "Simran Dewan",
  "fibcmis@manharpolymers.com": "Ali Abdou Mohamed Mohamed",
  "sumit.jaiswal@aptiv.com": "Abir Lal Mondal",
  "diffinummer@live.in": "Alwin Pb",
  "ats-curd-in@amazon.com": "Daniel Owen Nimmo",
  "jayesh.rao@kryfs.com": "Dinesh Kumar Jha",
  "shrutin@thelanguageskool.com": "Himanshu Bhalla",
  "yasser.hassan@experts.com.eg": "Jasmeet Kaur",
  "jyoti.balyan@alfazance.com": "Kunal Singh",
  "s396@tatastarbucks.com": "Mohsin Afzal Bhat",
  "linto.samuel@vensure.com": "Pritesh Dadarao Burange",
  "dhruv.jindal@amdocs.com": "Ratan Priya",
  "harsha.n@acumant.com": "Shiv Sompati",
  "sushanthb@nxtgen.com": "Dheeraj Kumar Raosaheb Patil",
  "saurav.das7@wipro.com": "Kelly",
  "mentorsunar@consultbtg.in": "Rimpy Srivastava",
  "support@albnsecurities.com": "Manish Bansal",
  "tarunika.verma-v@adityabirla.com": "Nikita Das",
  "gourav.khushalani@dynatechconsultancy.com": "Abhilakh Borgohain",
  "n.deena@icloude.com": "Divya R",
  "tm.spirehyd@i-smartservices.com": "Rakesh Kota Amarnath",
  "zakaullah@projectsbel.in": "Nirmala Gowda C",
  "chinmaya.kodankiri@thomsonreuters.com": "Khushi Dhingra",
  "bathina.saikrishna@hcltech.com": "Divyesh Tiwari",
  "nikhilkumar@industowers.com": "Akum Jung La",
  "shashank@tekhubinc.com": "Sana Sadiq Pathan",
  "jagadeesh_govindarajan@comcast.com": "Swati Rai",
  "saurabhkx2014@email.iimcal.ac.in": "Saif Hiyatullaha Munshi",
  "g.gandhi@tecnimont.in": "Aditya Kumar Tiwari",
  "ashwini_tj@comcast.com": "Kevin L",
  "shazia.khan@franklintempleton.com": "Parisha Gupta",
  "arivalagan@voc.sphier.com": "Maitri Dipak Bhansali",
  "santhoshkumar.panneerselvam@flex.com": "Avni Singh",
  "jaimeen.rana@linde.com": "Zaid Yousuf Wani",
  "nkp@somcable.com": "Anchal Bhatia",
  "edms.udaipur@enhira.com": "Saurabh Banerjee",
  "aratipropertiesltd@hyperkennect.in": "Umar Farooq",
  "vivek.gautam@pricol.com": "Tarun Monga",
  "nitinbharambe@rediffmail.com": "Deeksha Chaitanya",
  "keerthana.chandiran@avasoft.com": "Prity Bharti",
  "na@honeywell.com": "Kuldip Singh Parmar",
  "tuliprasad@deloitte.com": "Pooja Chauhan",
  "pratyushbmp@planetcast.com": "Abhishek R",
  "na@na.com": "Tarun Dwivedi",
  "hf_dstsupport@bandhanbank.com": "Anika Singh Rana",
  "lakshanika.madabhushi@marsh.com": "Aman Sinha",
  "thilahar.g@luminad.com": "Rahul Singh",
  "dinesh.rajendran@freshworks.com": "Gurpreet Kaur",
  "awadhesh.kumar@ocs.com": "Tamanna Alisha",
  "sandeep.sajwan@snu.edu.in": "Shalini Sharma",
  "pradip.pahari@dabur.com": "Gourav Garg",
  "daname3729@naprb.com": "Prashant Verma",
  "mithilks@iitk.ac.in": "Simran Dewan",
  "ravikiran.n@ohmemobility.com": "Ali Abdou Mohamed Mohamed",
  "shruti.singh@wellsfargo.com": "Abhishek G B",
  "shirly@ngsupplychain.com": "Abir Lal Mondal",
  "kanwal_singal2003@rediffmail.com": "Alwin Pb",
  "poojakumari@talentsocio.com": "Daniel Owen Nimmo",
  "yashavanth.shetty@versar.com": "Dinesh Kumar Jha",
  "business. head@hindflyingsolution.com": "Himanshu Bhalla",
  "manjeet.jaglan@maxlifeinsurance.com": "Jasmeet Kaur",
  "civildcprojects@aepl.co": "Kunal Singh",
  "lokesh.k@coforge.com": "Mohsin Afzal Bhat",
  "guruprasad.n@diageo.com": "Neha Tripathi",
  "amarjeet.singh.kalsi@accenture.com": "Pritesh Dadarao Burange",
  "vivek11.jadhav@nttdata.com": "Ratan Priya",
  "mallikarjun.jangamavibuti@carrier.com": "Shaik Sumaya Parvin",
  "sarnali.saha@bba.christuniversity.in": "Shiv Sompati",
  "nehaben.solanki@kotak.com": "Dheeraj Kumar Raosaheb Patil",
  "sharad.bansode@neclife.com": "Kelly",
  "shailendra.sharma@kyvos.io": "Rimpy Srivastava",
  "vijaya.bhanu@inspace.gov.in": "Manish Bansal",
  "dhilleeswararao.sadhu@cognizant.com": "Nikita Das",
  "maneesh.yadav@delhivery.com": "Abhilakh Borgohain",
  "aalokkumar@hitachisolutions.com": "Divya R",
  "manish.kapoor@agreeya.com": "Rakesh Kota Amarnath",
  "info@technosysinternational.com": "Nirmala Gowda C",
  "saurabh.k@fortune-it.co.in": "Khushi Dhingra",
  "sanket.mehta@genmills.com": "Divyesh Tiwari",
  "manjeet.yadav@bpl.in": "Akum Jung La",
  "gurpreet.singh@optiva.com": "Sana Sadiq Pathan",
  "amit.chakrapani@dvc.gov.in": "Swati Rai",
  "vijay.kumar@ibo.com": "Saif Hiyatullaha Munshi",
  "vinodkumar.d@adani.com": "Aditya Kumar Tiwari",
  "sindhu.kalluri@accenture.com": "Kevin L",
  "preeti.kundu.ec.2019@miet.ac.in": "Parisha Gupta",
  "ajay5.soni@ril.com": "Maitri Dipak Bhansali",
  "manoj.patil@igenesys.com": "Avni Singh",
  "naveengupta@msfl.in": "Zaid Yousuf Wani",
  "weng.gzb@shahi.co.in": "Anchal Bhatia",
  "sachin.shrivastava@cognizant.com": "Saurabh Banerjee",
  "manjunath.ramachandra@nexturn.com": "Umar Farooq",
  "sridevi.moturi@quadranttechnologies.com": "Tarun Monga",
  "tamil.selvi.mani@accenture.com": "Deeksha Chaitanya",
  "vishwaraj.chari@jkmail.com": "Prity Bharti",
  "anandkumar.sah@electronicpay.in": "Kuldip Singh Parmar",
  "rajesh.sawant@anived.com": "Pooja Chauhan",
  "neeraj.kashyap@clarivate.com": "Abhishek R",
  "senthilkumar_balasubramaniam@trimble.com": "Tarun Dwivedi",
};
