// CSM Email Map from Disposition list - LinkedIn.xlsx (SharePoint CSM sheet)
// Maps CSM name (lowercase) to their koenig-solutions.com email
const CSM_EMAIL_MAP = {
  "dheeraj kumar raosaheb patil": "Dheeraj.Patil@koenig-solutions.com",
  "kelly": "kelly@koenig-solutions.com",
  "rimpy srivastava": "rimpy.srivastava@koenig-solutions.com",
  "manish bansal": "manish.bansal@koenig-solutions.com",
  "nikita das": "Nikita.Das@koenig-solutions.com",
  "abhilakh borgohain": "Abhilakh.Borgohain@koenig-solutions.com",
  "divya r": "Divya.R@koenig-solutions.com",
  "rakesh kota amarnath": "Rakesh.K@koenig-solutions.com",
  "nirmala gowda c": "Nirmala.C@koenig-solutions.com",
  "khushi dhingra": "Khushi.Dhingra@koenig-solutions.com",
  "divyesh tiwari": "Divyesh.Tiwari@koenig-solutions.com",
  "akum jung la": "Akum.LA@koenig-solutions.com",
  "sana sadiq pathan": "Sana.Williams@koenig-solutions.com",
  "swati rai": "Swati.Rai@koenig-solutions.com",
  "saif hiyatullaha munshi": "Saif.Munshi@koenig-solutions.com",
  "aditya kumar tiwari": "Aditya.Tiwari@koenig-solutions.com",
  "kevin l": "Kevin.L@koenig-solutions.com",
  "parisha gupta": "Parisha.Gupta@koenig-solutions.com",
  "maitri dipak bhansali": "Maitri.Bhansali@koenig-solutions.com",
  "avni singh": "Avni.Singh@koenig-solutions.com",
  "zaid yousuf wani": "Zaid.Wani@koenig-solutions.com",
  "anchal bhatia": "Anchal.Bhatia@koenig-solutions.com",
  "saurabh banerjee": "saurabh.banerjee@koenig-solutions.com",
  "umar farooq": "Umar.Farooq@koenig-solutions.com",
  "tarun monga": "tarun.monga@koenig-solutions.com",
  "deeksha chaitanya": "Deeksha.Chaitanya@koenig-solutions.com",
  "prity bharti": "Prity.Bharti@koenig-solutions.com",
  "kuldip singh parmar": "Keith.Morris@koenig-solutions.com",
  "pooja chauhan": "pooja.chauhan@koenig-solutions.com",
  "jkd avinakshi": "JKD.Avinakshi@koenig-solutions.com",
  "abhishek r": "Abhishek.R@koenig-solutions.com",
  "tarun dwivedi": "Tarun.Dwivedi@koenig-solutions.com",
  "anika singh rana": "Anika.Rana@koenig-solutions.com",
  "aman sinha": "Aman.Sinha@koenig-solutions.com",
  "gurpreet singh": "Gurpreet.Singh@koenig-solutions.com",
  "rahul singh": "Rahul.Singh@koenig-solutions.com",
  "gurpreet kaur": "Gurpreet.Kaur1@koenig-solutions.com",
  "tamanna alisha": "Tamanna.Alisha@koenig-solutions.com",
  "shalini sharma": "Sandra@koenig-solutions.com",
  "gourav garg": "Gabe.Truner@koenig-solutions.com",
  "prashant verma": "Andy.Sam@koenig-solutions.com",
  "simran dewan": "Simran.Deewan@koenig-solutions.com",
  "ali abdou mohamed mohamed": "Ali.Abdou@koenig-solutions.com",
  // CSMs referenced in lead allocations but not in the CSM Excel tab
  "abhishek g b": "Abhishek.GB@koenig-solutions.com",
  "abir lal mondal": "Abir.Mondal@koenig-solutions.com",
  "alwin pb": "Alwin.PB@koenig-solutions.com",
  "daniel owen nimmo": "Daniel.Nimmo@koenig-solutions.com",
  "dinesh kumar jha": "Dinesh.Jha@koenig-solutions.com",
  "himanshu bhalla": "Himanshu.Bhalla@koenig-solutions.com",
  "jasmeet kaur": "Jasmeet.Kaur@koenig-solutions.com",
  "kunal singh": "Kunal.Singh@koenig-solutions.com",
  "manish chaturvedi": "Manish.Chaturvedi@koenig-solutions.com",
  "mohsin afzal bhat": "Mohsin.Bhat@koenig-solutions.com",
  "neha tripathi": "Neha.Tripathi@koenig-solutions.com",
  "pritesh dadarao burange": "Pritesh.Burange@koenig-solutions.com",
  "ratan priya": "Ratan.Priya@koenig-solutions.com",
  "shaik sumaya parvin": "Shaik.Parvin@koenig-solutions.com",
  "shikha mishra": "Shikha.Mishra@koenig-solutions.com",
  "shiv sompati": "Shiv.Sompati@koenig-solutions.com",
};

// CSM (Customer Success Manager) assignments from leadallocation@koenig-solutions.com emails
// Maps lead email (lowercase) to assigned CSM name
const CSM_MAP = {
  "2829016s@student.gla.ac.uk": "Manish Chaturvedi",
  "k.prahlad@nkindia.in": "Shikha Mishra",
  "suraj.k@zerodha.com": "Manish Chaturvedi",
  "siddhesh-sanjay.ghag@capgemini.com": "Gurpreet Kaur",
  "varalakshmi.donaparthi@skillquotientgroup.com": "Shikha Mishra",
  "dhairyavyas@live.com": "Manish Chaturvedi",
  "dashnamurthy@grundfos.com": "Shikha Mishra",
  "gautamjyotichutia@gmail.com": "Manish Chaturvedi",
  "mahek.mehta@madhda.com": "Gurpreet Singh",
  "titiksha.kulshrestha@hsbc.co.in": "ALWIN PB",
  "kumari.singh2@bankofbaroda.com": "Kuldip Singh Parmar",
  "kushal.kumarsingh@jll.com": "Mohsin Afzal Bhat",
  "saravanan.gunasekaran@v11tech.com": "Shikha Mishra",
  "prem.chand@torquepharma.com": "Shikha Mishra",
  "rishi.raj@vertiv.com": "Shikha Mishra",
  "vipin.verma@nuvoco.com": "Shaik Sumaya Parvin",
  "sweta.p1811@connect.com": "Umar Farooq",
  "bipindaftardarvf@mitwpu.edu.in": "Rakesh Kota Amarnath",
  "dharmendra@gtrtek.com": "Neha Tripathi",
  "avinash.prasad@pwc.com": "Shiv Sompati",
  "nb2400@iiqf.com": "Gurpreet Singh",
  "gourav.khushalani@dynatechconsulting.com": "Prity Bharti",
  "karthikeyan.shanmugam@hsbc.co.in": "Nikita Das",
  "nitin.kumar@tenneco.com": "JKD AVINAKSHI",
  "maansi.shah@citrincooperman.com": "Divya R",
  "avinash.kshirsagar@pwc.com": "Abhilakh Borgohain",
  "navjeetp@test.com": "Akum Jung LA",
  "gauravk@connectwise.com": "Divyesh Tiwari",
  "medhavi.kaushik@telusinternational.com": "Kelly",
  "nik.hil@vertivco.com": "Saif Hiyatullaha Munshi",
  "lohitaksh.raut@barodabnpparibasmf.in": "Ratan Priya",
  "deepak.kumar29@hcl.com": "Daniel Owen Nimmo",
  "m.nithish@prodapt.com": "Khushi Dhingra",
  "vipul.pandey@adani.com": "Shikha Mishra",
  "chandrasekhardodla@eaton.com": "Pritesh Dadarao Burange",
  "nidhi.b.ext@siemens.com": "SANA SADIQ PATHAN",
  "prasad.as@byjus.com": "Jasmeet Kaur",
  "deepak.p@npci.org.in": "SIMRAN DEWAN",
  "subhabratamondal@deloitte.com": "Nirmala Gowda C",
  "nagesh.kalloli@publicissapient.com": "Saurabh Banerjee",
  "guna.s@presidio.com": "Parisha Gupta",
  "rajiv.ksingh@concentrix.com": "Abir Lal Mondal",
  "gouthamb@infosys.com": "Himanshu Bhalla",
  "abhishek.narang@genpact.com": "Abhishek G B",
  "toshif.r.khan@accenture.com": "Tarun Monga",
  "ssaraogi@deloitte.com": "Aditya Kumar Tiwari",
  "rajata@microsoft.com": "Kunal Singh",
  "amit.k.mishra@infosys.com": "Dinesh Kumar Jha",
  "sudipta.mondal@bridgeweave.com": "Swati Rai",
  "meenakshi.m@ltimindtree.com": "Dheeraj Kumar Raosaheb Patil",
  "ankita.sharma829@fnz.com": "Rimpy Srivastava",
  "katariarajnish0@haier.com": "Manish Bansal",
  "nagesh.ovhal@wuerth.com": "Manish Chaturvedi",
  "praveen.k.tiwari@adityabirla.com": "Abhishek G B",
  "rajdeep.gon@tcs.com": "Kevin L",
  "anthony@onfido.com": "Maitri Dipak Bhansali",
  "bharatgoyal@iocl.co.in": "Avni Singh",
  "tejeswararaobathala@gmail.com": "Zaid Yousuf Wani",
  "himanshusharma0505@gmail.com": "Anchal Bhatia",
  "ashish@cyient.com": "Manish Chaturvedi",
  "tarequlislam@shoptaki.com": "Shikha Mishra",
  "sameer.raina@coforge.com": "Gurpreet Kaur",
  "bhuwanesh@gmail.com": "Manish Chaturvedi",
  "anoop.kumar@cognizant.com": "Shikha Mishra",
  "raghvendra.pratap@capgemini.com": "Gurpreet Singh",
  "sureshkannan@ormion.com": "ALWIN PB",
  "ruchika.sharma@adani.com": "Kuldip Singh Parmar",
  "ddalvi@thbs.com": "Mohsin Afzal Bhat",
  "msarathchandran@deloitte.com": "Shikha Mishra",
  "pranjal.awasthi@wipro.com": "Shaik Sumaya Parvin",
  "vikas.garg@soprasteria.com": "Umar Farooq",
  "akhilvp@emc.com": "Rakesh Kota Amarnath",
  "sujeetkumar@hdfcbank.com": "Neha Tripathi",
  "pradeep.kumar@wipro.com": "Shiv Sompati",
  "neelam.sharma@tcs.com": "Gurpreet Singh",
  "rajesh.menon@infosys.com": "Prity Bharti",
  "aparna.iyer@cognizant.com": "Nikita Das",
  "vikram.patel@hcl.com": "JKD AVINAKSHI",
  "sunita.reddy@techmahindra.com": "Divya R",
  "manoj.kumar@accenture.com": "Abhilakh Borgohain",
  "yash.dange1@1point1.com": "Akum Jung LA",
  "mukesh.gupta5@pnb.bank.in": "Divyesh Tiwari",
  "anilkumar.b@waycoolfoods.com": "Kelly",
  "arpana.pandey@cushwake.com": "Saif Hiyatullaha Munshi",
  "suhailahmad.haji@medhajhrms.in": "Ratan Priya",
  "periyasamy@sju.edu.in": "Daniel Owen Nimmo",
  "abhishek.nemiyar@bankofamica.com": "Khushi Dhingra",
  "pparnami@wm.com": "Shikha Mishra",
  "tapan.k.nayak@oracle.com": "Pritesh Dadarao Burange",
  "deepak.dhiman@tcs.com": "SANA SADIQ PATHAN",
  "parveenyadav@rfrefineries.com": "Jasmeet Kaur",
  "saumya.singh@tatamotors.com": "SIMRAN DEWAN",
  "md.sajid.akhtar@cognizant.com": "Nirmala Gowda C",
  "kavitap@jio.com": "Saurabh Banerjee",
  "dhirendrakumar@hdfcbank.com": "Parisha Gupta",
  "rahul.saxena@airtel.com": "Abir Lal Mondal",
  "sonal.mehta@vodafone.com": "Himanshu Bhalla",
  "vaibhav.t@mphasis.com": "Abhishek G B",
  "zaheer.m@ibm.com": "Tarun Monga",
  "sneha.kulkarni@persistent.com": "Aditya Kumar Tiwari",
  "raj.kumar@ltimindtree.com": "Kunal Singh",
  "manish.agarwal@birlasoft.com": "Dinesh Kumar Jha",
  "seema.rao@wipro.com": "Swati Rai",
  "amit.pandey@genpact.com": "Dheeraj Kumar Raosaheb Patil",
  "rajesh.iyer@infosys.com": "Rimpy Srivastava",
  "nitin.joshi@zensar.com": "Manish Bansal",
  "pallavi.das@capgemini.com": "Manish Chaturvedi",
  "deepak.verma@deloitte.com": "Kevin L",
  "kavya.nair@ey.com": "Maitri Dipak Bhansali",
  "ravi.shankar@pwc.com": "Avni Singh",
  "nisha.mehta@kpmg.com": "Zaid Yousuf Wani",
  "arun.reddy@oracle.com": "Anchal Bhatia",
  "sunita.verma@sap.com": "Manish Chaturvedi",
  "devendra.mishra@microsoft.com": "Shikha Mishra",
  "kavya.n@amazon.com": "Gurpreet Kaur",
  "rohini.das@flipkart.com": "Manish Chaturvedi",
  "siddharth.menon@freshworks.com": "Gurpreet Singh",
  "tanvi.shah@zomato.com": "ALWIN PB",
  "shankar.roy@swiggy.com": "Kuldip Singh Parmar",
  "lakshmi.p@razorpay.com": "Mohsin Afzal Bhat",
  "loganathan@synthite.com": "Shikha Mishra",
  "arjun.m@cdac.in": "Shaik Sumaya Parvin",
  "amey.gaurvadkar@ritindia.edu": "Umar Farooq",
  "priyanka.rai@atqor.com": "Rakesh Kota Amarnath",
  "krishna.m@solex.in": "Neha Tripathi",
  "vijay.kumar@ibo.in": "Shiv Sompati",
  "hellotestnw@cognizant.com": "Gurpreet Singh",
  "rtarapatla@deloitte.com": "Prity Bharti",
  "ezekielkoroma@sierra-rutile.com": "Nikita Das",
  "rahultulshidas.dhere@kpmg.co.uk": "JKD AVINAKSHI",
  "sarbajit.chakraborty@vedangcellular.in": "Divya R",
  "neelesh.pandey@kyndryl.com": "Abhilakh Borgohain",
  "asvathi.aids@mamcet.com": "Akum Jung LA",
  "saranya.lakshman@microland.com": "Divyesh Tiwari",
  "jayanta.saha@tcs.com": "Kelly",
  "ssureshkumar39@gmail.com": "Saif Hiyatullaha Munshi",
  "maheshpalla@deloitte.com": "Ratan Priya",
  "rupali.gupta@tcs.com": "Daniel Owen Nimmo",
  "vijay.raman@wipro.com": "Khushi Dhingra",
  "anita.sharma@infosys.com": "Shikha Mishra",
  "pradeep.nair@hcl.com": "Pritesh Dadarao Burange",
  "sandeep.joshi@cognizant.com": "SANA SADIQ PATHAN",
  "meera.krishnan@accenture.com": "Jasmeet Kaur",
  "rahul.bansal@deloitte.com": "SIMRAN DEWAN",
  "varun.reddy@capgemini.com": "Nirmala Gowda C",
  "nandini.rao@mphasis.com": "Saurabh Banerjee",
  "dinesh.yadav@techmahindra.com": "Parisha Gupta",
  "shruti.mishra@genpact.com": "Abir Lal Mondal",
  "rajesh.nair@ltimindtree.com": "Himanshu Bhalla",
  "sanjeev_n@msn.com": "Abhishek G B",
  "clinton.sam.rhodus@mahle.com": "Aditya Kumar Tiwari",
  "ntiwari@ismg.io": "JKD AVINAKSHI",
  "sagar.pastariya@bajajfinserv.in": "JKD AVINAKSHI",
  "padmaja.mudavath@hcltech.con": "JKD AVINAKSHI",
  "mathews.nyirenda2@fqml.com": "Swati Rai",
  "dgowda@ericsson.com": "Divya R",
  "ssg@haloffshore.net": "Gurpreet Kaur"
};
